In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('display.max_rows', None)

In [52]:
column_defs = pd.read_csv('/Users/nick/w266_nlp_project/data/table_col_definitions.csv', encoding = 'cp1252')
ticket_data = pd.read_csv('/Users/nick/w266_nlp_project/data/ticket_data_no_autoreports.csv', encoding = 'cp1252',error_bad_lines=False)#,dtype = str)

b'Skipping line 61796: expected 73 fields, saw 235\n'
b'Skipping line 104379: expected 73 fields, saw 107\n'

In [48]:
column_defs

,TABLE_NAME,COLUMN_NAME,ORDINAL_POSITION,COLUMN_DEFAULT,IS_NULLABLE,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH,NUMERIC_PRECISION
0,BugActions,BugActionID,1,NaN,NO,int,NaN,10.0
1,BugActions,BugID,2,NaN,NO,int,NaN,10.0
2,BugActions,UserID,3,NaN,NO,varchar,5.000000e+01,NaN
3,BugActions,ActionTime,4,NaN,NO,datetime,NaN,NaN
4,BugActions,AssignedID,5,NaN,NO,varchar,5.000000e+01,NaN
5,BugActions,Notes,6,NaN,NO,varchar,7.000000e+03,NaN
6,BugActions,StatusID,7,NaN,NO,varchar,5.000000e+01,NaN
7,BugActions,PriorityID,8,NaN,NO,varchar,5.000000e+01,NaN
8,BugActions,ContactID,9,NaN,YES,varchar,5.000000e+01,NaN
9,BugActions,UpdateType,10,NaN,YES,varchar,5.000000e+01,NaN
10,BugActions,ResolutionID,11,NaN,YES,int,NaN,10.0
11,BugActions,ClientTouched,12,NaN,YES,bit,NaN,NaN
12,BugActions,CodeChanged,13,NaN,YES,bit,NaN,NaN
13,BugActions,ClientEmailed,14,NaN,YES,bit,NaN,NaN
14,BugActions,ClientPhoned,15,NaN,YES,bit,NaN,NaN
15,BugActions,UserDepartment,16,NaN,YES,varchar,5.000000e+01,NaN
16,BugActions,UserPosition,17,NaN,YES,varchar,5.000000e+01,NaN
17,BugActions,NextBugActionID,18,NaN,YES,int,NaN,10.0
18,BugActions,LastTouchPrevToCloseID,19,NaN,YES,int,NaN,10.0
19,BugActions,OpenAfterCloseID,20,NaN,YES,int,NaN,10.0
20,BugActions,NextCloseConfirmedID,21,NaN,YES,int,NaN,10.0
21,BugActions,RawHours,22,NaN,YES,decimal,NaN,18.0
22,BugActions,BusinessHours,23,NaN,YES,decimal,NaN,18.0
23,BugActions,LastCloseID,24,NaN,YES,int,NaN,10.0
24,BugActions,ActionOrder,25,((0)),NO,int,NaN,10.0
25,BugActions,RedirectStatus,26,NaN,YES,varchar,2.000000e+01,NaN
26,Bugs,BugID,1,NaN,NO,int,NaN,10.0
27,Bugs,Title,2,NaN,NO,varchar,2.000000e+02,NaN
28,Bugs,Repro,3,NaN,YES,text,2.147484e+09,NaN
29,Bugs,Directory,4,NaN,YES,varchar,2.000000e+02,NaN
30,Bugs,ProductID,5,NaN,YES,varchar,5.000000e+01,NaN
31,Bugs,ReportedID,6,NaN,NO,varchar,5.000000e+01,NaN
32,Bugs,Description,7,NaN,YES,varchar,5.000000e+03,NaN
33,Bugs,compid,8,NaN,YES,int,NaN,10.0
34,Bugs,contactid,9,NaN,YES,int,NaN,10.0
35,Bugs,Originated,10,NaN,YES,varchar,5.000000e+01,NaN
36,Bugs,KBArticleID,11,NaN,YES,int,NaN,10.0
37,Bugs,CurrentResolutionID,12,NaN,YES,int,NaN,10.0
38,Bugs,OpenedTime,13,(getdate()),YES,datetime,NaN,NaN
39,Bugs,LastBugActionID,14,NaN,YES,int,NaN,10.0
40,Bugs,WasLow,15,((0)),NO,bit,NaN,NaN
41,Bugs,WasAssignedToDev,16,((0)),NO,bit,NaN,NaN
42,Bugs,LastBugActionStatus,17,NaN,YES,varchar,5.000000e+02,NaN
43,Bugs,NumBugActions,18,NaN,YES,int,NaN,10.0
44,Bugs,LastContact,19,NaN,YES,datetime,NaN,NaN
45,Bugs,WasEscalatedPastRepLevel,20,((0)),YES,bit,NaN,NaN
46,Bugs,WorkspaceID,21,NaN,YES,int,NaN,10.0
47,Bugs,Summary,22,NaN,YES,varchar,1.000000e+03,NaN
48,Bugs,ClientTemp,23,NaN,YES,varchar,2.500000e+01,NaN
49,Bugs,MajorityPriorityID,24,NaN,YES,varchar,5.000000e+01,NaN
50,Bugs,SupportFailbyDev,25,NaN,YES,bit,NaN,NaN
51,Bugs,SupportFailConfirm,26,NaN,YES,bit,NaN,NaN
52,Bugs,Classification,27,NaN,YES,varchar,3.000000e+01,NaN
53,Bugs,HighestPriorityID,28,NaN,YES,varchar,1.000000e+01,NaN
54,Bugs,owner,29,NaN,YES,varchar,5.000000e+01,NaN
55,Bugs,IsEFP,30,NaN,YES,bit,NaN,NaN
56,Bugs,LastRedirectStatus,31,NaN,YES,varchar,2.000000e+01,NaN
57,BugSummaryHistory,BugID,1,NaN,NO,int,NaN,10.0
58,BugSummaryHistory,ChangeDateTime,2,NaN,NO,datetime,NaN,NaN
59,BugSummaryHistory,Summary,3,NaN,NO,varchar,1.000000e+03,NaN
60,BugSummaryHistory,ClientTemp,4,NaN,NO,varchar,2.500000e+01,NaN
61,BugSummaryHistory,UserID,5,NaN,YES,varchar,5.000000e+01,NaN
62,KBArticles,ArticleID,1,NaN,NO,int,NaN,10.0
63,KBArticles,Title,2,NaN,NO,nvarchar,1.000000e+02,NaN
64,KBArticles,Description,3,NaN,NO,text,2.147484e+09,NaN
65,KBArticles,NumUses,4,0,NO,int,NaN,10.0
66,KBArticles,NumTimesEscalated,5,0,NO,int,NaN,10.0
67,KBArticles,DefaultPriorityID,6,('Normal'),NO,varchar,2.000000e+01,NaN
68,KBArticles,PackageID,7,((-1)),NO,int,NaN,10.0
69,KBArticles,ProductID,8,((-1)),NO,int,NaN,10.0
70,KBArticles,Active,9,((1)),NO,int,NaN,10.0
71,KBArticles,UserFriendlyDesc,10,(''),NO,nvarchar,1.000000e+02,NaN
72,KBArticles,SalesProductGroupID,11,((0)),NO,int,NaN,10.0
73,KBArticles,DefaultClassification,12,NaN,YES,varchar,5.000000e+01,NaN

In [36]:
ticket_data.tail()

,BugActionID,BugID,ActionUserID,ActionTime,AssignedID,Notes,StatusID,PriorityID,BAContactID,UpdateType,...,KBDescription,NumUses,NumTimesEscalated,DefaultPriorityID,PackageID,KBProductID,Active,UserFriendlyDesc,SalesProductGroupID,DefaultClassification
252442,},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252443,NaN,Normal,kfaust,2232967,2404,EFP: File Acknowledgment Failed (TFC),{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fon...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252444,\viewkind4\uc1\pard\f0\fs17\par,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252445,},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252446,NaN,0,0,Normal,0,0,1,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
ticket_data.BugActionID.unique()[0:100]

array(['2119447',
       '\\viewkind4\\uc1\\pard\\f0\\fs24 instructed client how to fix the TIN error\\par ',
       ']they tried to file on the 31st and it didn;t work\\par ',
       'informed them that the efile will be closed until 1/18\\par ',
       'issue resolved\\par ', 'closing ticket\\par ', '} ', nan,
       '\\viewkind4\\uc1\\pard\\f0\\fs17 Client wants to know the status of their file for w2 or a 1099 or 1042\\par',
       '}',
       '\\viewkind4\\uc1\\pard\\f0\\fs17 client had errors with a 1095 filing\\par',
       '2119462',
       '\\viewkind4\\uc1\\pard\\f0\\fs24 Client asked if she could upload her w2s and 1099-cs through Tax filing center \\par ',
       '\\par ',
       'I told her yes she could and confirmed she did her year end close out with GP \\par ',
       '-closing ticket\\par ',
       '\\viewkind4\\uc1\\pard\\fs20 Answer simple questions not regarding any troubleshooting or walkthrough.\\f1\\par',
       '\\viewkind4\\uc1\\pard\\f0\\fs17 CLient wanted to make sure she could upload forms with TFC\\par',
       '2119582',
       "\\viewkind4\\uc1\\pard\\f0\\fs24 Client called us and stated that several EE's were having issues logging into the workspace site.\\par ",
       'WSID: 2000838\\par ',
       'EE1: Hilary Evans  Email: hevans@hchin.org\\par ',
       'EE2: janet waters  Email: jaynet.waters@gmail.com\\par ',
       'step1) Remoted in with client.\\par ',
       'Step2) Verified that both Hillary and kristin had not verified their accounts.\\par ',
       'Step3) Checked to see if hillarys email was in use and it was',
       'Step4) Had client verify what email Janet waters was using\\par ',
       'step5) Verified janets email and sent her a PW reset.\\par ',
       "Closing ticket since this should fix their login issues with these 2 EE's\\par ",
       "\\viewkind4\\uc1\\pard\\fs20 An admin for GOES / GreenEmployee.com (formerly GreenPaycheck.com ) has contacted support stating that the employee can't sign in to GreenEmployee.com",
       "\\viewkind4\\uc1\\pard\\f0\\fs17 Client called us about several EE's having login issues\\par",
       '{\\colortbl ;\\red0\\green0\\blue0;}',
       '\\viewkind4\\uc1\\pard\\cf1\\f0\\fs20 Clients may have questions about or need basic assistance with employees signing in or with employee access settings. If they are encountering issues',
       '\\par', '\\f1 Tags: account', '2119519',
       '\\viewkind4\\uc1\\pard\\f0\\fs24 opened accidentally\\par ',
       'closing\\par ',
       '\\viewkind4\\uc1\\pard\\f0\\fs17 After running a sync',
       '\\viewkind4\\uc1\\pard\\f0\\fs17 open enrollments did not sync\\par',
       '2121069', '\\viewkind4\\uc1\\pard\\f0\\fs24 Error Message\\par ',
       'Error trying to set the text of a specified element on the page\\par ',
       'SubmissionID: PGG00603175', 'Working with: Payment US-ND Payment',
       'GO #1000273', '\\viewkind4\\uc1\\pard\\f0\\fs17 ND WH\\par',
       '\\viewkind4\\uc1\\pard\\fs20\\par', '2120315',
       '\\viewkind4\\uc1\\pard\\lang1033\\f0\\fs24 Paystubs are only showing up on the homepage for GE \\endash  see GE homepage.jpg\\par ',
       'The 1/3 paystub will not show up on the Paystub drop down on EE\\rquote s GE page \\endash  see GE missing.jpg\\par ',
       'The 01/03/2017 checks are not showing up under the admin payroll summary - Payroll Summary.jpg\\par ',
       'Call dropped (during power outage)',
       'Uploaded data for 01/03/17\\par ',
       '\\viewkind4\\uc1\\pard\\fs20 An administrator for GreenshadesOnline.com paystubs contacts support stating that certain paystubs are missing or no paystubs are visible on the site / no paystubs uploaded\\par',
       'This is only on the admin side.\\par',
       '\\viewkind4\\uc1\\pard\\f0\\fs24 Paystubs are only showing up on the homepage for GE \\fs17\\par',
       '2119534',
       '\\viewkind4\\uc1\\pard\\f0\\fs24 Client called saying they had a meeting scheduled with Martin this morning at 8AM est. Client needs a TFC 1095 onramp. Apparently this had been previously scheduled and something happened. She wants to get this knocked out ASAP if possible.\\par ',
       '\\viewkind4\\uc1\\pard\\fs20 Clients will often call us to request help in walking them through the product.  When these training requests or OnRamp requests are submitted',
       'Greenshades Center\\par', 'DownloadMyForm.com\\f1\\par',
       '\\viewkind4\\uc1\\pard\\f0\\fs24 Client needs a TFC 1095 onramp.\\fs17\\par',
       'Tags: TFC', '2119531',
       '{\\colortbl ;\\red31\\green73\\blue125;\\red56\\green86\\blue35;\\red5\\green99\\blue193;} ',
       '\\viewkind4\\uc1\\pard\\ltrpar\\f0\\fs24 client is only registered for 1099 on gc so i am going to tell them to use connector\\par ',
       '______________________\\par ', '1/03/17\\par ',
       '\\pard\\ltrpar\\cf1\\f1\\fs22 Hi Kordell',
       'I see you are only registered for 1099\\rquote s with the Greenshades center so for w2\\rquote s you want to use the connector.  Please let me know if that clarifies everything',
       'Thank you', '\\cf2\\b Will DiGiovanni\\par ',
       'Greenshades Tech Support\\par ', '888-255-3815 ext 1\\par ',
       '\\cf0\\b0\\f0\\fs24\\cf1\\f1\\fs22\\par ',
       '\\cf0\\b From:\\b0  Kordell Bauer [\\cf3\\ul <mailto:kordell@hitinc.org>\\cf0\\ulnone ] \\line\\b Sent:\\b0  Monday',
       'Do I upload my w-2 forms through the connector or the Greenshades center  need to know asap thanks\\par ',
       '\\pard\\ltrpar\\f0\\fs24\\par ',
       '\\viewkind4\\uc1\\pard\\fs20 Answer simple questions not regarding any troubleshooting or walkthrough.\\par',
       '\\cf1\\f1 There are also more specific question KBs', '\\f0\\par',
       'Year end forms yearendforms\\par',
       '(Previously) DownloadMyForm.com/DMF/DMF.com\\par',
       '\\viewkind4\\uc1\\pard\\f0\\fs17 client wants to know if they upload w2 with connector or greenshades center\\par',
       '2119589',
       '\\viewkind4\\uc1\\pard\\f0\\fs24 Client unable to open the payroll inspector\\par ',
       'sent her a zip file with update from P\\par ',
       'Had her copy them', 'Issue resolved\\par ',
       '\\viewkind4\\uc1\\pard\\f0\\fs17 Use this KB is client is having issues with the ACA Widgets for DPI\\par',
       '\\viewkind4\\uc1\\pard\\f0\\fs17 Unable to open the payroll inspector\\par',
       '2119540',
       '{\\colortbl ;\\red31\\green73\\blue125;\\red46\\green116\\blue181;\\red5\\green99\\blue193;} ',
       '\\viewkind4\\uc1\\pard\\ltrpar\\f0\\fs24 Answered question. (Step 8 of YEF) Closing.\\par ',
       '\\pard\\ltrpar\\b\\f1\\fs22 From:\\b0  Greenshades Support \\line\\b Sent:\\b0  Thursday',
       '\\cf1 Hi Natalie',
       'I can answer your question.  Are you using Year-End Forms?  That would be done on Step 8. \\par ',
       '\\cf2\\b\\f2\\fs18 --\\par ', 'Ericca Harvey\\f1\\par '],
      dtype=object)